services:
  foo:
    image: wikirecs
    blkio_config:
       weight: 300
       weight_device:
         - path: /dev/sda
           weight: 400
       device_read_bps:
         - path: /dev/sdb
           rate: '12mb'
       device_read_iops:
         - path: /dev/sdb
           rate: 120
       device_write_bps:
         - path: /dev/sdb
           rate: '1024k'
       device_write_iops:
         - path: /dev/sdb
           rate: 30
  backend:
    image: wikirecs
    volumes:
      - db-data:/etc/data
volumes:
  db-data:
    name: "wikirecs_db"